sudo: required
language: generic

services:
  - docker

befor_install:
  - docker build -t aziz24/react-tests -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true aziz24/react-tests npm test

after_success:
  - docker build -t aziz24/multi-client ./client  
  - docker build -t aziz24/multi-nginx ./nginx  
  - docker build -t aziz24/multi-server ./server 
  - docker build -t aziz24/multi-worker ./worker 
  # log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push aziz24/multi-client
  - docker push aziz24/multi-nginx
  - docker push aziz24/multi-server
  - docker push aziz24/multi-worker