sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aziz24/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aziz24/react-test npm test

after_success:
  - docker build -t aziz24/multi-client:latest ./client
  - docker build -t aziz24/multi-nginx:latest ./nginx
  - docker build -t aziz24/multi-server:latest ./server
  - docker build -t aziz24/multi-worker:latest ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push aziz24/multi-client:latest
  - docker push aziz24/multi-nginx:latest
  - docker push aziz24/multi-server:latest
  - docker push aziz24/multi-worker:latest
deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-3
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-3-883879838305
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
